### PR TITLE
Rename files to start with number

### PR DESCRIPTION
**Pull request by omi10859**
All tutorial files has been renamed to start with numbers so that they are in order 
issue: https://github.com/intermine/intermine-ws-python-docs/issues/20

### CODE REVIEW

**Comment by omi10859** [comment]
@yochannah @julie-sullivan please review

**Comment by julie-sullivan** [comment]
Looks great! That makes the tutorials easy to use, good idea.

Can you update the links too? 1c8f8586430003a6ed75d765b46d02e10dc67af0

Thanks! :)

**Comment by omi10859** [comment]
Good to go!! :)
@julie-sullivan @yochannah

**Comment by yochannah** [comment]
Thumbs up from me - tested links, all good. @julie-sullivan happy to merge.

@omi10859 THANK YOU! <3

**Pull request merged**
