### PR TITLE
Added thirteenth tutorial

### PR DESCRIPTION
**Pull request by nupurgunwant**
This tutorial is in reference to [PR #5](https://github.com/intermine/intermine-ws-python/pull/5) in InterMine Python Client. 
It explains the usage of three useful functions ie `getInfo()`, `getData()` and `getMines()`

### CODE REVIEW

**Comment by yochannah** [comment]
@nupurgunwant In order to get the first cell to run I had to modify the first line to be `from intermine import registry` - does that sound right? I could be doing something wrong since python is not my strong suit.

**Comment by nupurgunwant** [comment]
Yes, that's right. I should have included that line in the tutorial

**Comment by yochannah** [comment]
One further comment for this tutorial: Maybe we could reverse the tutorial steps? Imagine this scenario: 

1. I don't know much about InterMine, so I run `getMines` to find a mine for my favourite organism.
2. oh, cool! I see that there are two mines that return my organism, and I choose to use flymine. Now, I run `getInfo` to see what we know about the mine. (side note: it also might be nice for getInfo to return a mine that has neighbourhood information in it - human or fly are good examples here). 
3. It looks like flymine is indeed the InterMine of my dreams, so *now* I want to see what data is in it! `getData`

**Comment by nupurgunwant** [comment]
@yochannah Sure, that seems like a legit way to describe that. I have made the changes

**Comment by yochannah** [comment]
The changes all look good! I'd like to merge, but one more tiny request - could we rename the file? @julie-sullivan quite intelligently suggested that if we're doing a tutorial one of the first things anyone might want to see is the mine that has the data they know and love. We could sneakily insert this as tutorial 0 - and to match with the filename schema we have now that would be 00-tutorial.ipynb, plus changing the heading at the top of the notebook.

Once that's done I will accept the PR - thanks!

**Comment by nupurgunwant** [comment]
@yochannah made the changes. Do tell me if I am missing out anything

**Comment by yochannah** [comment]
Looks good! Thanks for your patience with all my requests ;)

**Pull request merged**
