### PR TITLE
15-tutorial.ipynb

### PR DESCRIPTION
**Pull request by Sanat-Mishra**
Simple examples to show how one can manipulate the model to get information regarding the class'.

### CODE REVIEW

**Comment by yochannah** [comment]
Hey @Sanat-Mishra! Could you rename the file to 15-tutorial.ipynb to match the other files in the folder? Right now jupyter seems to think it's plain text:

image

**Comment by Sanat-Mishra** [comment]
@yochannah Done!

**Comment by yochannah** [comment]
Hmm, I'm still having problems opening it - any suggestions? 

"Unreadable Notebook: /Users/yo/projects/intermine-ws-python-docs/15-tutorial.ipynb NotJSONError('Notebook does not appear to be JSON: \' {"cell_type": "markdown",\\n "metadat...',)"

image

**Comment by yochannah** [comment]
Oh, I think I have an idea - look at the start of tutorial 14:

```json
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
```

tutorial 15 is missing the opening cells bit:

```json
 {"cell_type": "markdown",
   "metadata": {},
   "source": [
```

**Comment by yochannah** [comment]
@Sanat-Mishra Let me know when this is fixed and ready to test!

**Comment by Sanat-Mishra** [comment]
@yochannah Thanks for the lead. Will let you know once its ready to test!

**Comment by yochannah** [comment]
Hey @Sanat-Mishra, this is looking good and I can run it as a jupyter notebook now - nice! :)

A small comment - in the guidance text cells it might be nice to make more use of [markdown](https://guides.github.com/features/mastering-markdown/#syntax), especially backticks to highlight method and variable names. e.g.

instead of

>Notice that we used make_path() in the process. This function helps us construct paths and inspect whether it is valid or not, or as in here, utilise it to get more information from the model.

put backticks ` around make_path(): 

>Notice that we used `make_path()` in the process. This function helps us construct paths and inspect whether it is valid or not, or as in here, utilise it to get more information from the model.

Section headers might be nice too. 

Other than that, I think this could be useful! Let's ask @rachellyne what she thinks when she gets back from holiday.

**Comment by Sanat-Mishra** [comment]
@yochannah Sure! Will do it soon.

**Pull request merged**
