### PR TITLE
 correct some typos and add some words for readability

### PR DESCRIPTION
**Pull request by Persdre**
correct obvious typos and add some link words as well as delete some useless expression

### CODE REVIEW

**Comment by Persdre** [comment]
> I have reviewed the changes. They look good to me.

I am still reviewing it. And some outputs are not correct now due to changes of source code. I will update this request in a few days.

**Comment by asherpasha** [comment]
I think we should merge more often.

**Comment by Persdre** [comment]
> I think we should merge more often.

haha Yo said there are too many PRs.

**Comment by yochannah** [comment]
discussed with @Persdre - these typos will get fixed later but this doesn't merge nicely - 100% my fault for taking too long to merge 😞

**Pull request closed without merging**
